# Generated by Django 3.2 on 2023-01-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20230121_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'permissions': [('has_score_permission', 'User Has Score Permission')]},
        ),
    ]
