# Generated by Django 3.2 on 2022-12-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20221211_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='title',
            new_name='name',
        ),
    ]
