# Generated by Django 3.2 on 2023-02-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_rename_numbers_shippingaddress_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(max_length=32),
        ),
    ]
